### ISSUE TITLE
Krypton configuration settings

### ISSUE THREAD

**Issue by whoabuddy** [Daemon-Technologies/Mining-Local-Server#11]
Three questions that came up when reviewing the [Krypton configuration file](https://github.com/Daemon-Technologies/Mining-Local-Server/blob/master/conf/miner-Krypton.toml):

Does the Krypton miner still need to exit at this block height, or can it run indefinitely? If it is set, maybe it should be `Contest Duration / 2min blocks + a little padding`?

`process_exit_at_block_height = 5130`

Why is the burn fee cap increased from the default here? 

`burn_fee_cap = 80000`

What does this seed value relate to, since miners are encouraged to put in their own BTC/STX addresses before starting the miner?

`seed = "6d7803411d5799cb9f070e68d776d2471467ded8cf528ea8d32ba76c32e4948e01"`

**Comment by whoabuddy** [comment]
Also, a few people are reporting the following message when running the mining bot with Krypton, should this be removed now?

`Node successfully reached the end of the ongoing 5130 blocks epoch. Terminating in 30s and restart to keep participating`

**Comment by gavinisagi** [comment]
> Three questions that came up when reviewing the [Krypton configuration file](https://github.com/Daemon-Technologies/Mining-Local-Server/blob/master/conf/miner-Krypton.toml):
> 
> Does the Krypton miner still need to exit at this block height, or can it run indefinitely? If it is set, maybe it should be `Contest Duration / 2min blocks + a little padding`?
> 
> `process_exit_at_block_height = 5130`
> 
> Why is the burn fee cap increased from the default here?
> 
> `burn_fee_cap = 80000`
> 
> What does this seed value relate to, since miners are encouraged to put in their own BTC/STX addresses before starting the miner?
> 
> `seed = "6d7803411d5799cb9f070e68d776d2471467ded8cf528ea8d32ba76c32e4948e01"`

The ```seed``` and ```burn_fee_cap``` is not necessary, Mining-Local-Server will refresh them by new parameters transferred by Mining-Bot.

About ```process_exit_at_block_height ``` I remember I deleted in Krypton feature update, I will take a look. It should be deleted.

**Comment by gavinisagi** [comment]
Fixed ```process_exit_at_block_height``` in https://github.com/Daemon-Technologies/Mining-Local-Server/pull/12
