### ISSUE TITLE
Mining-Local-Server attempts to open port 8000

### ISSUE THREAD

**Issue by christianblaze** [Daemon-Technologies/Mining-Local-Server#23]
When starting Mining-Local-Server using "npm start", server.js attempts to open port 8000 which is used by Mining-Bot.
Removing lines 147 - 149 found in server.js may resolve the issue: 

clientApp.listen(8000, () => {
    console.log(`Mining-Bot Client listening at http://localhost:8000`)
})

**Comment by gavinisagi** [comment]
> When starting Mining-Local-Server using "npm start", server.js attempts to open port 8000 which is used by Mining-Bot.
> Removing lines 147 - 149 found in server.js may resolve the issue:
> 
> clientApp.listen(8000, () => {
> console.log(`Mining-Bot Client listening at http://localhost:8000`)
> })

@christianblaze  It is designed so.
For decreasing the environment building of users, I integrate the Mining-Bot into Mining-Local-Server. When you use ```yarn start``` launching the new Mining-Bot, you could open localhost:8000 and have a look.

**Comment by gavinisagi** [comment]
Close then
