### ISSUE TITLE
wrong config file updated

### ISSUE THREAD

**Issue by friedger** [Daemon-Technologies/Mining-Local-Server#9]
`updateMinerToml` updates the file `miner-Krypton.toml`, while the start command is used with config file `miner.toml`

**Comment by gavinisagi** [comment]
> `updateMinerToml` updates the file `miner-Krypton.toml`, while the start command is used with config file `miner.toml`


I think I fix it in https://github.com/Daemon-Technologies/Mining-Local-Server/commit/12c814d3dc1879a9f362f4c8400617e71426471f

You can have a check in latest version.
